### ISSUE TITLE
Many error about undefined reference

### ISSUE THREAD

**Issue by SUSIEE01** [shamanDevel/DiffDVR#4] opened 2022-05-22 04:40 UTC
I have encountered new problems again. The log output is as follows

```
[ 84%] Linking CXX executable Gui
CMakeFiles/Gui.dir/main.cpp.o: In function `c10::IValue::toDouble() const':
main.cpp:(.text._ZNK3c106IValue8toDoubleEv[_ZNK3c106IValue8toDoubleEv]+0x91): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
CMakeFiles/Gui.dir/main.cpp.o: In function `c10::IValue::toInt() const':
main.cpp:(.text._ZNK3c106IValue5toIntEv[_ZNK3c106IValue5toIntEv]+0x91): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
CMakeFiles/Gui.dir/main.cpp.o: In function `c10::IValue::toComplexDouble() const':
main.cpp:(.text._ZNK3c106IValue15toComplexDoubleEv[_ZNK3c106IValue15toComplexDoubleEv]+0xc6): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
CMakeFiles/Gui.dir/main.cpp.o: In function `c10::IValue::toTensor() const &':
main.cpp:(.text._ZNKR3c106IValue8toTensorEv[_ZNKR3c106IValue8toTensorEv]+0xc9): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
CMakeFiles/Gui.dir/main.cpp.o: In function `c10::intrusive_ptr<c10::TensorImpl, c10::UndefinedTensorImpl>::retain_()':
main.cpp:(.text._ZN3c1013intrusive_ptrINS_10TensorImplENS_19UndefinedTensorImplEE7retain_Ev[_ZN3c1013intrusive_ptrINS_10TensorImplENS_19UndefinedTensorImplEE7retain_Ev]+0xc0): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
CMakeFiles/Gui.dir/main.cpp.o:main.cpp:(.text._ZN3c1013intrusive_ptrINS_6ivalue13ComplexHolderENS_6detail34intrusive_target_default_null_typeIS2_EEE7retain_Ev[_ZN3c1013intrusive_ptrINS_6ivalue13ComplexHolderENS_6detail34intrusive_target_default_null_typeIS2_EEE7retain_Ev]+0xc0): more undefined references to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)' follow
CMakeFiles/Gui.dir/visualizer.cpp.o: In function `c10::IndexError::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
visualizer.cpp:(.text._ZN3c1010IndexErrorCI2NS_5ErrorEENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN3c1010IndexErrorCI5NS_5ErrorEENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x2c): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
CMakeFiles/Gui.dir/visualizer.cpp.o: In function `at::AutoNonVariableTypeMode::AutoNonVariableTypeMode(bool)':
visualizer.cpp:(.text._ZN2at23AutoNonVariableTypeModeC2Eb[_ZN2at23AutoNonVariableTypeModeC5Eb]+0x9a): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
CMakeFiles/Gui.dir/visualizer.cpp.o: In function `torch::detail::TensorDataContainer::TensorDataContainer(std::initializer_list<torch::detail::TensorDataContainer>)':
visualizer.cpp:(.text._ZN5torch6detail19TensorDataContainerC2ESt16initializer_listIS1_E[_ZN5torch6detail19TensorDataContainerC5ESt16initializer_listIS1_E]+0x22c): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
visualizer.cpp:(.text._ZN5torch6detail19TensorDataContainerC2ESt16initializer_listIS1_E[_ZN5torch6detail19TensorDataContainerC5ESt16initializer_listIS1_E]+0x306): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/Gui.dir/visualizer.cpp.o: In function `torch::detail::TensorDataContainer::convert_to_tensor(c10::TensorOptions) const':
visualizer.cpp:(.text._ZNK5torch6detail19TensorDataContainer17convert_to_tensorEN3c1013TensorOptionsE[_ZNK5torch6detail19TensorDataContainer17convert_to_tensorEN3c1013TensorOptionsE]+0x335): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
visualizer.cpp:(.text._ZNK5torch6detail19TensorDataContainer17convert_to_tensorEN3c1013TensorOptionsE[_ZNK5torch6detail19TensorDataContainer17convert_to_tensorEN3c1013TensorOptionsE]+0x3d2): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
CMakeFiles/Gui.dir/visualizer.cpp.o: In function `torch::detail::TensorDataContainer::pretty_print_recursive(std::ostream&) const::{lambda()#1}::operator()() const':
visualizer.cpp:(.text._ZZNK5torch6detail19TensorDataContainer22pretty_print_recursiveERSoENKUlvE_clEv[_ZZNK5torch6detail19TensorDataContainer22pretty_print_recursiveERSoENKUlvE_clEv]+0x3d0): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/Gui.dir/visualizer.cpp.o: In function `torch::detail::TensorDataContainer::pretty_print_recursive(std::ostream&) const::{lambda()#2}::operator()() const':
visualizer.cpp:(.text._ZZNK5torch6detail19TensorDataContainer22pretty_print_recursiveERSoENKUlvE0_clEv[_ZZNK5torch6detail19TensorDataContainer22pretty_print_recursiveERSoENKUlvE0_clEv]+0x484): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/Gui.dir/visualizer.cpp.o: In function `torch::detail::TensorDataContainer::pretty_print_recursive(std::ostream&) const':
visualizer.cpp:(.text._ZNK5torch6detail19TensorDataContainer22pretty_print_recursiveERSo[_ZNK5torch6detail19TensorDataContainer22pretty_print_recursiveERSo]+0x2f9): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
CMakeFiles/Gui.dir/visualizer.cpp.o: In function `torch::detail::TensorDataContainer::fill_tensor(at::Tensor&) const':
visualizer.cpp:(.text._ZNK5torch6detail19TensorDataContainer11fill_tensorERN2at6TensorE[_ZNK5torch6detail19TensorDataContainer11fill_tensorERN2at6TensorE]+0x100): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
visualizer.cpp:(.text._ZNK5torch6detail19TensorDataContainer11fill_tensorERN2at6TensorE[_ZNK5torch6detail19TensorDataContainer11fill_tensorERN2at6TensorE]+0x2ea): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
visualizer.cpp:(.text._ZNK5torch6detail19TensorDataContainer11fill_tensorERN2at6TensorE[_ZNK5torch6detail19TensorDataContainer11fill_tensorERN2at6TensorE]+0x462): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
visualizer.cpp:(.text._ZNK5torch6detail19TensorDataContainer11fill_tensorERN2at6TensorE[_ZNK5torch6detail19TensorDataContainer11fill_tensorERN2at6TensorE]+0x510): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
CMakeFiles/Gui.dir/visualizer.cpp.o: In function `torch::autograd::AutogradMeta::set_requires_grad(bool, c10::TensorImpl*)':
visualizer.cpp:(.text._ZN5torch8autograd12AutogradMeta17set_requires_gradEbPN3c1010TensorImplE[_ZN5torch8autograd12AutogradMeta17set_requires_gradEbPN3c1010TensorImplE]+0xd7): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/Gui.dir/visualizer.cpp.o: In function `torch::autograd::AutogradMeta::AutogradMeta(c10::TensorImpl*, bool, torch::autograd::Edge)':
visualizer.cpp:(.text._ZN5torch8autograd12AutogradMetaC2EPN3c1010TensorImplEbNS0_4EdgeE[_ZN5torch8autograd12AutogradMetaC5EPN3c1010TensorImplEbNS0_4EdgeE]+0x1e7): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
visualizer.cpp:(.text._ZN5torch8autograd12AutogradMetaC2EPN3c1010TensorImplEbNS0_4EdgeE[_ZN5torch8autograd12AutogradMetaC5EPN3c1010TensorImplEbNS0_4EdgeE]+0x2e9): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/Gui.dir/visualizer.cpp.o: In function `at::TensorAccessor<int, 3ul, at::DefaultPtrTraits, long> at::Tensor::accessor<int, 3ul>() const &':
visualizer.cpp:(.text._ZNKR2at6Tensor8accessorIiLm3EEENS_14TensorAccessorIT_XT0_ENS_16DefaultPtrTraitsElEEv[_ZNKR2at6Tensor8accessorIiLm3EEENS_14TensorAccessorIT_XT0_ENS_16DefaultPtrTraitsElEEv]+0xe4): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/Gui.dir/visualizer.cpp.o: In function `at::TensorAccessor<float, 4ul, at::DefaultPtrTraits, long> at::Tensor::accessor<float, 4ul>() const &':
visualizer.cpp:(.text._ZNKR2at6Tensor8accessorIfLm4EEENS_14TensorAccessorIT_XT0_ENS_16DefaultPtrTraitsElEEv[_ZNKR2at6Tensor8accessorIfLm4EEENS_14TensorAccessorIT_XT0_ENS_16DefaultPtrTraitsElEEv]+0xe4): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/Gui.dir/visualizer.cpp.o: In function `at::TensorAccessor<float, 3ul, at::DefaultPtrTraits, long> at::Tensor::accessor<float, 3ul>() const &':
visualizer.cpp:(.text._ZNKR2at6Tensor8accessorIfLm3EEENS_14TensorAccessorIT_XT0_ENS_16DefaultPtrTraitsElEEv[_ZNKR2at6Tensor8accessorIfLm3EEENS_14TensorAccessorIT_XT0_ENS_16DefaultPtrTraitsElEEv]+0xe4): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/Gui.dir/visualizer.cpp.o: In function `c10::intrusive_ptr<c10::VariableVersion::VersionCounter, c10::detail::intrusive_target_default_null_type<c10::VariableVersion::VersionCounter> > c10::intrusive_ptr<c10::VariableVersion::VersionCounter, c10::detail::intrusive_target_default_null_type<c10::VariableVersion::VersionCounter> >::make<unsigned int&>(unsigned int&)':
visualizer.cpp:(.text._ZN3c1013intrusive_ptrINS_15VariableVersion14VersionCounterENS_6detail34intrusive_target_default_null_typeIS2_EEE4makeIJRjEEES6_DpOT_[_ZN3c1013intrusive_ptrINS_15VariableVersion14VersionCounterENS_6detail34intrusive_target_default_null_typeIS2_EEE4makeIJRjEEES6_DpOT_]+0x12d): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
CMakeFiles/Gui.dir/tf_editor.cpp.o: In function `at::GenericPackedTensorAccessor<float, 3ul, at::DefaultPtrTraits, int> at::Tensor::generic_packed_accessor<float, 3ul, at::DefaultPtrTraits, int>() const &':
tf_editor.cpp:(.text._ZNKR2at6Tensor23generic_packed_accessorIfLm3ENS_16DefaultPtrTraitsEiEENS_27GenericPackedTensorAccessorIT_XT0_ET1_T2_EEv[_ZNKR2at6Tensor23generic_packed_accessorIfLm3ENS_16DefaultPtrTraitsEiEENS_27GenericPackedTensorAccessorIT_XT0_ET1_T2_EEv]+0xe4): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../renderer/libRenderer.a(volume.cpp.o): In function `renderer::Volume::dataGpu(int) const':
volume.cpp:(.text+0x25fe): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../renderer/libRenderer.a(volume.cpp.o): In function `renderer::Volume::dataCpu(int) const':
volume.cpp:(.text+0x272e): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../renderer/libRenderer.a(volume.cpp.o): In function `c10::StorageImpl::StorageImpl(c10::StorageImpl::use_byte_size_t, unsigned long, c10::DataPtr, c10::Allocator*, bool)':
volume.cpp:(.text._ZN3c1011StorageImplC2ENS0_15use_byte_size_tEmNS_7DataPtrEPNS_9AllocatorEb[_ZN3c1011StorageImplC5ENS0_15use_byte_size_tEmNS_7DataPtrEPNS_9AllocatorEb]+0x131): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
../renderer/libRenderer.a(volume.cpp.o): In function `at::Context::getDeviceFromPtr(void*, c10::DeviceType)':
volume.cpp:(.text._ZN2at7Context16getDeviceFromPtrEPvN3c1010DeviceTypeE[_ZN2at7Context16getDeviceFromPtrEPvN3c1010DeviceTypeE]+0xed): undefined reference to `c10::DeviceTypeName[abi:cxx11](c10::DeviceType, bool)'
volume.cpp:(.text._ZN2at7Context16getDeviceFromPtrEPvN3c1010DeviceTypeE[_ZN2at7Context16getDeviceFromPtrEPvN3c1010DeviceTypeE]+0x159): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../renderer/libRenderer.a(volume.cpp.o): In function `at::from_blob(void*, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::TensorOptions const&)':
volume.cpp:(.text._ZN2at9from_blobEPvN3c108ArrayRefIlEES3_RKNS1_13TensorOptionsE[_ZN2at9from_blobEPvN3c108ArrayRefIlEES3_RKNS1_13TensorOptionsE]+0x1a7): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../renderer/libRenderer.a(volume.cpp.o): In function `c10::intrusive_ptr<c10::StorageImpl, c10::detail::intrusive_target_default_null_type<c10::StorageImpl> > c10::intrusive_ptr<c10::StorageImpl, c10::detail::intrusive_target_default_null_type<c10::StorageImpl> >::make<c10::StorageImpl::use_byte_size_t, unsigned long&, c10::DataPtr, c10::Allocator*&, bool&>(c10::StorageImpl::use_byte_size_t&&, unsigned long&, c10::DataPtr&&, c10::Allocator*&, bool&)':
volume.cpp:(.text._ZN3c1013intrusive_ptrINS_11StorageImplENS_6detail34intrusive_target_default_null_typeIS1_EEE4makeIJNS1_15use_byte_size_tERmNS_7DataPtrERPNS_9AllocatorERbEEES5_DpOT_[_ZN3c1013intrusive_ptrINS_11StorageImplENS_6detail34intrusive_target_default_null_typeIS1_EEE4makeIJNS1_15use_byte_size_tERmNS_7DataPtrERPNS_9AllocatorERbEEES5_DpOT_]+0x1d7): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
../renderer/libRenderer.a(volume.cpp.o): In function `c10::intrusive_ptr<c10::StorageImpl, c10::detail::intrusive_target_default_null_type<c10::StorageImpl> >::retain_()':
volume.cpp:(.text._ZN3c1013intrusive_ptrINS_11StorageImplENS_6detail34intrusive_target_default_null_typeIS1_EEE7retain_Ev[_ZN3c1013intrusive_ptrINS_11StorageImplENS_6detail34intrusive_target_default_null_typeIS1_EEE7retain_Ev]+0xc0): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
../renderer/libRenderer.a(volume.cpp.o): In function `at::GenericPackedTensorAccessor<float, 4ul, at::DefaultPtrTraits, int> at::Tensor::generic_packed_accessor<float, 4ul, at::DefaultPtrTraits, int>() const &':
volume.cpp:(.text._ZNKR2at6Tensor23generic_packed_accessorIfLm4ENS_16DefaultPtrTraitsEiEENS_27GenericPackedTensorAccessorIT_XT0_ET1_T2_EEv[_ZNKR2at6Tensor23generic_packed_accessorIfLm4ENS_16DefaultPtrTraitsEiEENS_27GenericPackedTensorAccessorIT_XT0_ET1_T2_EEv]+0xe4): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../renderer/libRenderer.a(camera.cpp.o): In function `renderer::Camera::viewportFromLookAt(at::Tensor const&, at::Tensor const&, at::Tensor const&)':
camera.cpp:(.text+0xfed): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
camera.cpp:(.text+0x10d7): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
camera.cpp:(.text+0x11e9): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
camera.cpp:(.text+0x12a7): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../renderer/libRenderer.a(camera.cpp.o):camera.cpp:(.text+0x1391): more undefined references to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
../renderer/libRenderer.a(camera.cpp.o):(.data.rel.ro._ZTVN5torch8autograd7CppNodeIN8renderer19GenerateRayFunctionEEE[_ZTVN5torch8autograd7CppNodeIN8renderer19GenerateRayFunctionEEE]+0x20): undefined reference to `torch::autograd::Node::name[abi:cxx11]() const'
../renderer/libRenderer.a(tf_utils.cpp.o): In function `renderer::TFUtils::findBestFit(at::Tensor const&, at::Tensor const&, kernel::TFMode, int, float, at::Tensor const*, float)':
tf_utils.cpp:(.text+0x1a15): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
tf_utils.cpp:(.text+0x1ab7): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
tf_utils.cpp:(.text+0x1b5e): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
tf_utils.cpp:(.text+0x1c48): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
tf_utils.cpp:(.text+0x1d18): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../renderer/libRenderer.a(tf_utils.cpp.o):tf_utils.cpp:(.text+0x1e3c): more undefined references to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
../renderer/libRenderer.a(tf_utils.cpp.o):(.data.rel.ro._ZTVN5torch8autograd7CppNodeIN8renderer22PreshadeVolumeFunctionEEE[_ZTVN5torch8autograd7CppNodeIN8renderer22PreshadeVolumeFunctionEEE]+0x20): undefined reference to `torch::autograd::Node::name[abi:cxx11]() const'
../renderer/libRenderer.a(renderer.cpp.o): In function `renderer::Renderer::checkInputs(renderer::RendererInputsHost const&, int&, int&, int&, int&, int&, int&, bool&, bool)':
renderer.cpp:(.text+0x105d): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
renderer.cpp:(.text+0x1141): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
renderer.cpp:(.text+0x1231): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
renderer.cpp:(.text+0x1350): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
renderer.cpp:(.text+0x142f): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../renderer/libRenderer.a(renderer.cpp.o):renderer.cpp:(.text+0x157e): more undefined references to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
../renderer/libRenderer.a(renderer_cuda_impl.cu.o): In function `c10::Allocator::raw_allocate(unsigned long)':
tmpxft_00007de6_00000000-6_renderer_cuda_impl.compute_72.cudafe1.cpp:(.text._ZN3c109Allocator12raw_allocateEm[_ZN3c109Allocator12raw_allocateEm]+0xc1): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
../renderer/libRenderer.a(renderer_cuda_impl.cu.o): In function `c10::Allocator::raw_deallocate(void*)':
tmpxft_00007de6_00000000-6_renderer_cuda_impl.compute_72.cudafe1.cpp:(.text._ZN3c109Allocator14raw_deallocateEPv[_ZN3c109Allocator14raw_deallocateEPv]+0x9b): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/home/qianyi/anaconda3/envs/py38torch18/lib/python3.8/site-packages/torch/lib/libtorch_python.so: undefined reference to `PyThread_tss_alloc'
/home/qianyi/anaconda3/envs/py38torch18/lib/python3.8/site-packages/torch/lib/libtorch_python.so: undefined reference to `PyThread_tss_create'
/home/qianyi/anaconda3/envs/py38torch18/lib/python3.8/site-packages/torch/lib/libtorch_python.so: undefined reference to `PyThread_tss_get'
/home/qianyi/anaconda3/envs/py38torch18/lib/python3.8/site-packages/torch/lib/libtorch_python.so: undefined reference to `PyThread_tss_set'
collect2: error: ld returned 1 exit status
gui/CMakeFiles/Gui.dir/build.make:356: recipe for target 'gui/Gui' failed
make[2]: *** [gui/Gui] Error 1
CMakeFiles/Makefile2:297: recipe for target 'gui/CMakeFiles/Gui.dir/all' failed
make[1]: *** [gui/CMakeFiles/Gui.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
```
I found that `PyThread_tss_alloc`、`PyThread_tss_create`、`PyThread_tss_get` and  `PyThread_tss_set` are in file `pythread.pxd`.
I'm not sure what caused this and how to solve this. Some say this is caused by the version of libtorch. But my pytorch version is 1.8.0.
I sincerely looking forward to your help.

**Comment by SUSIEE01** [comment] 2022-05-22 07:08
I add `add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)` in CMakeLists.txt and many error disappear.
Now log output like this:
```
[ 84%] Linking CXX executable Gui
/home/qianyi/anaconda3/envs/py38torch18/lib/python3.8/site-packages/torch/lib/libtorch_python.so: undefined reference to `PyThread_tss_alloc'
/home/qianyi/anaconda3/envs/py38torch18/lib/python3.8/site-packages/torch/lib/libtorch_python.so: undefined reference to `PyThread_tss_create'
/home/qianyi/anaconda3/envs/py38torch18/lib/python3.8/site-packages/torch/lib/libtorch_python.so: undefined reference to `PyThread_tss_get'
/home/qianyi/anaconda3/envs/py38torch18/lib/python3.8/site-packages/torch/lib/libtorch_python.so: undefined reference to `PyThread_tss_set'
collect2: error: ld returned 1 exit status
gui/CMakeFiles/Gui.dir/build.make:356: recipe for target 'gui/Gui' failed
make[2]: *** [gui/Gui] Error 1
CMakeFiles/Makefile2:297: recipe for target 'gui/CMakeFiles/Gui.dir/all' failed
make[1]: *** [gui/CMakeFiles/Gui.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by shamanDevel** [comment] 2022-05-23 09:49
Hi,
the problem is, I personally develop on Windows and use only a headless Linux server to run the optimizations with disabled GUI. This makes it hard for me to reproduce your error. There might be some compiler errors due to incompatibilities, e.g. missing localtime_r or MAX_PATH. But apparently, you have fixed them already because you report errors during the linker stage.

Anyway, your linker errors are happening somewhere in PyTorch / LibTorch. This is out of my control, I can only guess. Maybe you installed some incompatible torch versions (python version, CUDA version). 
Have you searched for the problem on the PyTorch forums or StackOverflow? Apparently, this issue happens from time to time, e.g. https://github.com/pytorch/pytorch/issues/40415

**Comment by SUSIEE01** [comment] 2022-05-29 04:29
I still haven't solved the problem...
I just use  `environment.yml` to create my environment in anaconda so that many library versions should be correct...Let me confirm that my version matches yours.
```
torch version : 1.8.0
python version : 3.8.8
CUDA version : 11.1
```
Your CUDA version may be 11.0 just as you say in `readme.md`. But `torch==1.8.0` does not seem to fit `cuda==11.0`...

**Comment by shamanDevel** [comment] 2022-05-29 07:23
Hi, on the headless Linux server, I only run the renderer backend with the PyTorch bindings. There is no X-Server or any other kind of display available so I can't test the GUI. On my local machine I'm running Windows with a regular CMake + MSVC-compilation pipeline.
If you look at the `environment.yml`, I'm using CUDA 11.1 and PyTorch `1.8.0=py3.8_cuda11.1_cudnn8.0.5_0`. Note that CUDA 11.1 is installed globally on my system.

Once those dependencies are installed, I use the following script to compile the library:

compile-library-server.sh
```
echo CMake
mkdir build
cd build
cmake -DTORCH_PATH=~/anaconda3/envs/py38torch18/lib/python3.8/site-packages/torch -DRENDERER_ONLY_RESOURCES=ON -DRENDERER_USE_DOUBLE_PRECISION=OFF ..
make VERBOSE=true
cd ..

echo Setup-Tools build
python setup.py build
cp build/lib.linux-x86_64-3.8/pyrenderer.cpython-38-x86_64-linux-gnu.so bin/

echo Test
cd bin
python -c "import torch; print(torch.__version__); import pyrenderer;"
```

setup.py
```
from setuptools import setup
from torch.utils.cpp_extension import BuildExtension, CUDAExtension, _get_cuda_arch_flags
import os
import glob
import itertools

_arch_flags = _get_cuda_arch_flags()
print('arch flags:', _arch_flags)

_root = os.path.split(os.path.abspath(__file__))[0]
print("root path:", _root)
if not os.path.exists(os.path.join(_root, 'build/__cmrc_Renderer-kernels')):
    print("No resources found, did you run CMake beforehand?")
    exit(-1)
def get_files(base):
    fx1 = glob.iglob(base + "/**/*.cu", recursive=True)
    fx2 = glob.iglob(base + "/**/*.cpp", recursive=True)
    fx3 = glob.iglob(base + "/**/*.c", recursive=True)
    fx = itertools.chain(fx1, fx2, fx3)
    return [os.path.relpath(f, _root) for f in fx]

_renderer_files = get_files(os.path.join(_root, 'renderer'))
_binding_files = get_files(os.path.join(_root, 'bindings'))
_resource_files = get_files(os.path.join(_root, 'build/__cmrc_Renderer-kernels/intermediate')) +\
    ['build/__cmrc_Renderer-kernels/lib.cpp']
_thirdparty_files = get_files(os.path.join(_root, 'third-party/lz4/lib'))
print("renderer files:", _renderer_files)
print("binding files:", _binding_files)
print("resource files:", _resource_files)
print("third party files:", _thirdparty_files)

_include_dirs = [
    '%s/renderer'%_root,
    '%s/third-party/cuMat'%_root,
    '%s/third-party/cuMat/third-party'%_root,
    '%s/third-party/magic_enum/include'%_root,
    '%s/third-party/cudad/include/cudAD'%_root,
    '%s/third-party/tinyformat'%_root,
    '%s/third-party/nlohmann'%_root,
    '%s/third-party/lz4/lib'%_root,
    '%s/build/_cmrc/include'%_root,
    '/usr/include',
]

_libraries = [
    'cuda',
    'nvrtc',
    'curand',
]

_common_args = [
    '-std=c++17',
    '-DNVCC_ARGS="%s"'%_arch_flags[0],
    '-DRENDERER_RUNTIME_COMPILATION=1',
    '-DUSE_DOUBLE_PRECISION=0',
    '-DCDUMAT_SINGLE_THREAD_CONTEXT=1',
    '-DTHRUST_IGNORE_CUB_VERSION_CHECK=1',
    '-DRENDERER_BUILD_CPU_KERNELS=0',
]

setup(
    name='pyrenderer',
    ext_modules=[
        CUDAExtension('pyrenderer',
            _renderer_files+_binding_files+_resource_files+_thirdparty_files,
            extra_compile_args = {
                'cxx': _common_args,
                'nvcc': _common_args+["--extended-lambda"]
            },
            include_dirs = _include_dirs,
            libraries = _libraries),
    ],
    cmdclass={
        'build_ext': BuildExtension
    })

```

This uses PyTorch's built-in compilation system. But you can only build the renderer+bindings with that, not the GUI. Maybe you can try this out as a first step?

**Comment by SUSIEE01** [comment] 2022-05-29 16:10
Sincerely thanks for your detailed reply!!!
Good news that I finally compile successfully!!!
Now I can try to reproduce the results although without GUI...BTW, is the dataset not public?

**Comment by shamanDevel** [comment] 2022-05-29 17:08
Good to hear! I will also keep my eyes open if I stumble upon something that might lead to the issues with the GUI on Linux.
I will close this issue then, if you have further questions, just open another issue.

**Closed by shamanDevel** 2022-05-29 17:08 UTC
